[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true }
bytes = { workspace = true }
bytemuck = "1.24.0"
jpegxl-rs = "0.11.2"
kd-tree = "0.6.1"
tap = { workspace = true }

[lints]
workspace = true
